package kr.co.landfuture.api.def;

public final class SqlAbi {

        public static String sqlAbiCols = "        SELECT 										"
                        + "        a.appointed_date ad,                                                         "
                        + "        a.appointed_status              st,                                          "
                        + "        a.taker_name                    tn /* 경매계 */,                             "
                        + "        a.court_name,                                                                "
                        + "        a.court_code,                                                                "
                        + "        a.sa_num,                                                                    "
                        + "        a.realty_num                    r,                                           "
                        + "        Ifnull(a.bldg_area, 0)          ba,                                          "
                        + "        Ifnull(u.b_area, 0)             b_u,                                         "
                        + "        Ifnull(s.b_area, 0)             b_s,                                         "
                        + "        a.land_no_right                 l_n_right /* 대지권없음 */,                  "
                        + "        Ifnull(a.land_area, 0)          la,                                          "
                        + "        Ifnull(u.l_area, 0)             l_u,                                         "
                        + "        Ifnull(s.l_area, 0)             l_s,                                         "
                        + "        Group_concat(DISTINCT (b.idx2)) b_i2 /* 지분이 들어간 문구 */,               "
                        + "        Group_concat(DISTINCT (l.idx2)) l_i2 /* 지분이 들어간 문구 */,               "
                        + "        Group_concat(DISTINCT (c.sp))   sp                                           "
                        + " /* 손으로 입력된 문제점이라 생각되어지는 이유 - 작업 시 참조용 */                   ";
        public static String sqlAbiFrom = " FROM   cjs_collection_4.after_basic_info a "
                        + "        LEFT JOIN cjs_collection_4.after_bldg_report b                               "
                        + "               ON a.court_code = b.court_code                                        "
                        + "                  AND a.sa_num = b.sa_num                                            "
                        + "                  AND a.realty_num = b.realty_num                                    "
                        + "                  AND a.appointed_date = b.sale_date                                 "
                        + "        LEFT JOIN cjs_collection_4.after_land_report l                               "
                        + "               ON a.court_code = l.court_code                                        "
                        + "                  AND a.sa_num = l.sa_num                                            "
                        + "                  AND a.realty_num = l.realty_num                                    "
                        + "                  AND a.appointed_date = l.sale_date                                 "
                        + "        LEFT JOIN admin_lf.abi_ur u                                                  "
                        + "               ON a.court_code = u.cc                                                "
                        + "                  AND a.sa_num = u.sn                                                "
                        + "                  AND a.realty_num = u.rn                                            "
                        + "                  AND a.appointed_date = u.sd                                        "
                        + "        LEFT JOIN admin_lf.abi_aa s                                                  "
                        + "               ON a.court_code = s.cc                                                "
                        + "                  AND a.sa_num = s.sn                                                "
                        + "                  AND a.realty_num = s.rn                                            "
                        + "                  AND a.appointed_date = s.sd                                        "
                        + "        LEFT JOIN admin_lf.abi_comm c                                                "
                        + "               ON a.court_code = c.cc                                                "
                        + "                  AND a.sa_num = c.sn                                                ";

        public static String sqlAbiWhere = " WHERE  1 = 1 "
                        + "        AND u.st IN ( '진행', '신건', '유찰' )                                       "
                        + "        AND ( a.appointed_date >= Date_format(Date_add(Now(), INTERVAL +0 day),      "
                        + "                                  '%Y.%m.%d')                                        "
                        + "              AND a.appointed_date <= Date_format(Date_add(Now(),                    "
                        + "                                                  INTERVAL +14 day),                 "
                        + "                                      '%Y.%m.%d') )                                  "
                        + "        /* 매각기일 기간 */                                                          "
                        + "        AND ( ( ( ( Cast(a.bldg_area AS signed) - Cast(u.b_area AS signed) ) > 30    "
                        + "                   OR ( Cast(a.bldg_area AS signed) IS NULL                          "
                        + "                        AND Cast(u.b_area AS signed) != 0 )                          "
                        + "                   OR ( Cast(a.land_area AS signed) - Cast(u.l_area AS signed) )     "
                        + "                      > 30                                                           "
                        + "                   OR ( Cast(a.land_area AS signed) IS NULL                          "
                        + "                        AND Cast(u.l_area AS signed) != 0 )                          "
                        + "                   OR u.sn IS NULL )                                                 "
                        + "                AND ( ( Cast(a.bldg_area AS signed) - Cast(s.b_area AS signed) )     "
                        + "                      > 30                                                           "
                        + "                       OR ( Cast(a.bldg_area AS signed) IS NULL                      "
                        + "                            AND Cast(s.b_area AS signed) != 0 )                      "
                        + "                       OR ( Cast(a.land_area AS signed) -                            "
                        + "                            Cast(s.l_area AS signed) ) >                             "
                        + "                          30                                                         "
                        + "                       OR ( Cast(a.land_area AS signed) IS NULL                      "
                        + "                            AND Cast(s.l_area AS signed) != 0 )                      "
                        + "                       OR s.sn IS NULL ) )                                           "
                        + "               /* OR a.appointed_status != u.st */                                   "
                        + "               OR ( ( a.bldg_area IS NULL                                            "
                        + "                      AND a.land_area IS NULL )                                      "
                        + "                    AND ( u.b_area != 0                                              "
                        + "                           OR u.l_area != 0 )                                        "
                        + "                    AND ( s.b_area != 0                                              "
                        + "                           OR s.l_area != 0 ) ) )                                    ";
        public static String sqlAbiGroupBy = " GROUP  BY a.court_code, "
                        + "           a.sa_num,                                                                 "
                        + "           a.realty_num                                                              ";

        public static String sqlAbiOrderBy = " ORDER  BY ad desc, " + " ( Cast(Ifnull(a.bldg_area, 10000) AS signed) - "
                        + "             Cast(u.b_area AS signed) ) / (                                          "
                        + "                     Cast(u.b_area AS signed) + 1 ) DESC,                            "
                        + "           a.appointed_date DESC,                                                    "
                        + "           ( Cast(a.land_area AS signed) - Cast(u.l_area AS signed) ) / (            "
                        + "           Cast(u.l_area AS signed) + 1 ) DESC                                       ";

}
